export const FETCH_RECCOMENDATION_REQUEST = 'reccomendationdata/fetchReccomendationdataRequest';
export const FETCH_RECCOMENDATION_SUCCESS = 'reccomendationdata/fetchReccomendationdataSuccess';
export const FETCH_RECCOMENDATION_FAILURE = 'reccomendationdata/fetchReccomendationdataFailure';